"""yt-factory-backed video generation worker with optional auto-publish."""

from __future__ import annotations

import asyncio
from datetime import datetime
from typing import Any

import httpx

from app.api.v1.posts import CreatePostRequest, create_internal_post
from app.config import get_settings
from app.core.db import get_supabase
from app.core.errors import NotFoundError
from app.core.webhook_dispatcher import dispatch_event
from app.services.notification_service import create_notification
from app.services.video_templates import get_template
from app.workers.celery_app import celery_app


def _video_prompt(video_job: dict) -> str:
    style = f" in {video_job['style']} style" if video_job.get("style") else ""
    return (
        f"Create a {video_job['format']} {video_job['language']} video about "
        f"{video_job['topic']} for {video_job['mode']} content{style}."
    )


def _provider_headers() -> dict[str, str]:
    headers = {"Content-Type": "application/json"}
    if get_settings().yt_factory_api_key:
        headers["Authorization"] = f"Bearer {get_settings().yt_factory_api_key}"
    return headers


def _extract_generation_result(payload: dict[str, Any], *, fallback_job_id: str) -> dict[str, Any]:
    result = payload.get("result")
    if isinstance(result, dict):
        merged = {**payload, **result}
    else:
        merged = payload

    provider_job_id = (
        merged.get("provider_job_id")
        or merged.get("job_id")
        or merged.get("id")
        or fallback_job_id
    )
    return {
        "provider_job_id": provider_job_id,
        "status": (merged.get("status") or "completed").lower(),
        "output_url": merged.get("output_url") or merged.get("video_url"),
        "status_url": merged.get("status_url"),
        "raw": merged,
    }


async def _poll_until_complete(
    client: httpx.AsyncClient,
    *,
    provider_job_id: str,
    initial_status_url: str | None,
) -> dict[str, Any]:
    settings = get_settings()
    status_url = initial_status_url
    if not status_url:
        base_url = settings.yt_factory_base_url
        if not base_url:
            raise RuntimeError("YT_FACTORY_BASE_URL is not configured")
        status_url = f"{base_url.rstrip('/')}/api/v1/pipelines/{provider_job_id}"

    deadline = asyncio.get_running_loop().time() + settings.yt_factory_timeout_seconds
    while True:
        response = await client.get(status_url, headers=_provider_headers())
        response.raise_for_status()
        result = _extract_generation_result(response.json(), fallback_job_id=provider_job_id)
        if result["status"] in {"completed", "succeeded"} and result["output_url"]:
            result["status"] = "completed"
            return result
        if result["status"] in {"failed", "error", "cancelled"}:
            raise RuntimeError(result["raw"].get("error") or "yt-factory generation failed")
        if asyncio.get_running_loop().time() >= deadline:
            raise TimeoutError("Timed out while waiting for yt-factory output")
        await asyncio.sleep(settings.yt_factory_poll_interval_seconds)


async def _run_yt_factory(video_job: dict) -> dict[str, Any]:
    settings = get_settings()
    if not settings.yt_factory_base_url:
        raise RuntimeError("YT_FACTORY_BASE_URL is not configured")

    payload: dict[str, Any] = {
        "topic": video_job["topic"],
        "mode": video_job["mode"],
        "language": video_job["language"],
        "format": video_job["format"],
        "style": video_job.get("style"),
        "prompt": _video_prompt(video_job),
        "metadata": {"contentflow_video_id": video_job["id"]},
    }

    template_id = video_job.get("template")
    if template_id:
        tmpl = get_template(template_id)
        if tmpl:
            payload["template"] = tmpl.to_yt_factory_params()

    async with httpx.AsyncClient(timeout=settings.yt_factory_timeout_seconds) as client:
        response = await client.post(
            f"{settings.yt_factory_base_url.rstrip('/')}/api/v1/pipelines/run",
            headers=_provider_headers(),
            json=payload,
        )
        response.raise_for_status()
        result = _extract_generation_result(response.json(), fallback_job_id=video_job["id"])
        if result["status"] == "completed" and result["output_url"]:
            return result
        return await _poll_until_complete(
            client,
            provider_job_id=result["provider_job_id"],
            initial_status_url=result["status_url"],
        )


def _default_platform_options(video_job: dict, platforms: list[str]) -> dict[str, dict[str, Any]]:
    title = str(video_job["topic"])
    description = f"{video_job['mode']} explainer generated by ContentFlow."
    options: dict[str, dict[str, Any]] = {}
    for platform in platforms:
        if platform == "youtube":
            options[platform] = {"title": title, "description": description, "privacy": "public"}
        elif platform == "tiktok":
            options[platform] = {"title": title}
        elif platform == "instagram":
            options[platform] = {"caption": title}
    return options


def _parse_scheduled_for(raw_value: Any) -> datetime | None:
    if isinstance(raw_value, datetime):
        return raw_value
    if isinstance(raw_value, str) and raw_value:
        return datetime.fromisoformat(raw_value)
    return None


async def _auto_publish_video(video_job: dict, output_url: str) -> dict | None:
    auto_publish = video_job.get("auto_publish") or {}
    if not auto_publish.get("enabled"):
        return None

    platforms = auto_publish.get("platforms") or []
    if not platforms:
        return None

    request = CreatePostRequest(
        text=video_job["topic"],
        platforms=platforms,
        media_urls=[output_url],
        media_type="video",
        scheduled_for=_parse_scheduled_for(auto_publish.get("scheduled_for")),
        platform_options=_default_platform_options(video_job, platforms),
    )
    return await create_internal_post(
        video_job["owner_id"],
        request,
        workspace_id=video_job.get("workspace_id"),
    )


async def _load_video_job(video_id: str, owner_id: str) -> dict:
    sb = get_supabase()
    row = (
        sb.table("video_jobs")
        .select("*")
        .eq("id", video_id)
        .eq("owner_id", owner_id)
        .maybe_single()
        .execute()
        .data
    )
    if not row:
        raise NotFoundError("Video job", video_id)
    return row


async def run_video_generation(video_id: str, owner_id: str) -> dict:
    """Run yt-factory generation, persist the result, and optionally auto-publish."""
    sb = get_supabase()
    sb.table("video_jobs").update({"status": "processing"}).eq("id", video_id).execute()
    video_job = await _load_video_job(video_id, owner_id)

    try:
        generated = await _run_yt_factory(video_job)
        output_url = generated["output_url"]
        updates: dict[str, Any] = {
            "status": "completed",
            "provider_job_id": generated["provider_job_id"],
            "output_url": output_url,
        }

        created_post = await _auto_publish_video(video_job, output_url)
        if created_post:
            auto_publish = dict(video_job.get("auto_publish") or {})
            auto_publish["post_id"] = created_post["id"]
            auto_publish["post_status"] = created_post["status"]
            updates["auto_publish"] = auto_publish

        sb.table("video_jobs").update(updates).eq("id", video_id).execute()
        await dispatch_event(
            owner_id,
            "video.completed",
            {
                "video_id": video_id,
                "output_url": output_url,
                "provider_job_id": generated["provider_job_id"],
            },
        )
        try:
            create_notification(
                user_id=owner_id,
                type="video_ready",
                title="Video ready",
                body="Your video has been generated and is ready to view.",
                link_url=f"/videos/{video_id}",
            )
        except Exception:
            pass
    except Exception as exc:
        sb.table("video_jobs").update({"status": "failed"}).eq("id", video_id).execute()
        await dispatch_event(
            owner_id,
            "video.failed",
            {"video_id": video_id, "error": str(exc)},
        )
        raise

    return await _load_video_job(video_id, owner_id)


@celery_app.task(name="contentflow.generate_video")
def generate_video_task(video_id: str, owner_id: str) -> dict:
    return asyncio.run(run_video_generation(video_id, owner_id))
