from fastapi import APIRouter

from app.api.v1 import (
    accounts,
    admin,
    analytics,
    api_keys,
    audit,
    billing,
    bombs,
    comments,
    consent,
    domains,
    email_verify,
    legal,
    members,
    notification_prefs,
    notifications,
    onboarding,
    posts,
    predict,
    privacy,
    schedules,
    sheets_upload,
    shopsync,
    trending,
    usage,
    users,
    videos,
    webhooks,
    workspaces,
    ytboost,
    ytboost_analytics,
)

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(posts.router)
api_router.include_router(videos.router)
api_router.include_router(bombs.router)
api_router.include_router(comments.router)
api_router.include_router(predict.router)
api_router.include_router(schedules.router)
api_router.include_router(usage.router)
api_router.include_router(accounts.router)
api_router.include_router(analytics.router)
api_router.include_router(webhooks.router)
api_router.include_router(trending.router)
api_router.include_router(api_keys.router)
api_router.include_router(audit.router)
api_router.include_router(admin.router)
api_router.include_router(billing.router)
api_router.include_router(workspaces.router)
api_router.include_router(members.router)
api_router.include_router(domains.router)
api_router.include_router(onboarding.router)
api_router.include_router(email_verify.router)
api_router.include_router(notification_prefs.router)
api_router.include_router(notifications.router)
api_router.include_router(privacy.router)
api_router.include_router(consent.router)
api_router.include_router(legal.router)
api_router.include_router(users.router)
api_router.include_router(ytboost.router)
api_router.include_router(ytboost_analytics.router)
api_router.include_router(shopsync.router)
api_router.include_router(sheets_upload.router)
