"""Test script: Naver Blog Playwright automation.

Usage:
    # Step 1: Setup session (manual login)
    python scripts/test_naver_blog_playwright.py login

    # Step 2: Test post
    python scripts/test_naver_blog_playwright.py post

    # Step 3: Test via adapter interface
    python scripts/test_naver_blog_playwright.py adapter
"""
from __future__ import annotations

import asyncio
import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


async def cmd_login() -> None:
    """Open browser for manual Naver login and save session."""
    from app.services.naver_blog_playwright import NaverBlogPlaywright

    client = NaverBlogPlaywright()
    print(f"Session path: {client.session_path}")
    print("=" * 50)
    print("Chromium 브라우저가 열립니다.")
    print("네이버 로그인 페이지에서 직접 로그인해주세요.")
    print("로그인 완료 후 자동으로 세션이 저장됩니다.")
    print("제한시간: 5분")
    print("=" * 50)
    await client.setup_session()
    if client.has_session():
        print("\n[OK] Session saved!")
    else:
        print("\n[FAIL] Login failed or timed out. Try again.")


async def cmd_post() -> None:
    """Test posting a blog entry with AI-generated images."""
    from app.services.blog_image_generator import generate_blog_images
    from app.services.naver_blog_playwright import NaverBlogPlaywright

    client = NaverBlogPlaywright()

    if not client.has_session():
        print("No session file. Run: python scripts/test_naver_blog_playwright.py login")
        return

    title = "ContentFlow AI Image Test"
    content = (
        "ContentFlow AI image generation test post.\n"
        "This post was created automatically via Playwright.\n"
        "Images were generated by Claude + pollinations.ai.\n"
        "Please delete after verifying.\n"
        "\n"
        "ContentFlow is a service that automatically distributes\n"
        "YouTube content to multiple channels including blogs,\n"
        "Instagram, TikTok, and more."
    )

    print(f"Blog ID: {client.blog_id}")
    print(f"Session: {client.session_path}")

    # Generate AI images
    print("Generating AI images via Claude + pollinations.ai...")
    images = await generate_blog_images(title, content)
    image_paths = [str(p) for p in images]
    print(f"Generated {len(image_paths)} images")
    for p in image_paths:
        print(f"  - {p}")

    print("\nPosting blog entry...\n")

    result = await client.post(
        title=title,
        content=content,
        images=image_paths,
        tags=["ContentFlow", "AI", "test", "automation"],
    )

    print(f"\nResult: {result}")


async def cmd_adapter() -> None:
    """Test posting via the NaverBlogAdapter interface."""
    from app.adapters.base import MediaSpec
    from app.adapters.naver_blog import NaverBlogAdapter

    adapter = NaverBlogAdapter()

    result = await adapter.publish(
        text=(
            "어댑터 인터페이스 테스트입니다.\n"
            "NaverBlogAdapter.publish()를 통해 작성되었습니다.\n"
            "확인 후 삭제해주세요."
        ),
        media=[],
        options={
            "title": "ContentFlow 어댑터 테스트",
            "tags": ["ContentFlow", "어댑터테스트"],
        },
        credentials={},
    )

    print(f"\nPublishResult: success={result.success}, url={result.url}")
    if result.error:
        print(f"Error: {result.error}")


async def main() -> None:
    if len(sys.argv) < 2:
        print(__doc__)
        return

    cmd = sys.argv[1].lower()
    if cmd == "login":
        await cmd_login()
    elif cmd == "post":
        await cmd_post()
    elif cmd == "adapter":
        await cmd_adapter()
    else:
        print(f"Unknown command: {cmd}")
        print(__doc__)


if __name__ == "__main__":
    asyncio.run(main())
